## See the NOTICE file distributed with this work for additional
## information regarding copyright ownership.
##
## This is free software; you can redistribute it and/or modify it
## under the terms of the GNU Lesser General Public License as
## published by the Free Software Foundation; either version 2.1 of
## the License, or (at your option) any later version.
##
## This software is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this software; if not, write to the Free
## Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
## 02110-1301 USA, or see the FSF site: http://www.fsf.org.
##
## The goal of this action is to help developers automatically detect missing updates to files derived from templates.
## It works by running gradlew after each commit.
## If this results in files being updated, it means that gradlew should have been run and its output should have been
## added to the commit.
## The action then ends with an error.
name: Gradlew Check

on:
  push:
    branches: [ master ]

jobs:
  gradlew-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Gradle
        run: ./gradlew

      - name: Check for changed files
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: Files were modified by Gradle build"
            echo "Changed files:"
            git status --porcelain
            git diff
            exit 1
          else
            echo "Success: No files were modified"
          fi